Repository PaddlePaddle/Paddle2ONNX, pull requests merged in 2024-05, with the labels that each got.

#1249 [Doc][Build] Update en docs
  README.md
  README_en.md
  docs/en/compile_local.md
  docs/zh/compile_local.md
Labels: Doc, Build

#1253 Add test for bitwise_and op
  paddle2onnx/mapper/nn/layer_norm.cc
  tests/test_bitwise_and.py
Labels: Operator(New), CI

#1257 [ONNX][Update] Update ONNX Version to 1.16.0
  .gitmodules
  CMakeLists.txt
  paddle2onnx/mapper/activation.cc
  paddle2onnx/mapper/exporter.cc
  paddle2onnx/mapper/exporter.h
  paddle2onnx/mapper/mapper.h
  paddle2onnx/mapper/quantize_helper.cc
  paddle2onnx/mapper/tensor/atan2.cc
  paddle2onnx/mapper/tensor/reduce_logsumexp.h
  paddle2onnx/optimizer/convert_fp32_to_fp16.cc
  paddle2onnx/optimizer/paddle2onnx_optimizer.cc
Labels: Build, ONNX(Version)

#1259 [Pybind][Update] Update ONNX Version to 2.12.0
  .gitmodules
  CMakeLists.txt
Labels: Build, Pybind(Version)

#1261 [ONNX][Version] Update IR Version
  VERSION_NUMBER
  paddle2onnx/mapper/exporter.cc
  paddle2onnx/mapper/onnx_helper.cc
  paddle2onnx/mapper/onnx_helper.h
Labels: ONNX(Version)

#1264 add unbind op
  paddle2onnx/mapper/tensor/fill_constant.cc
  paddle2onnx/mapper/tensor/reduce_prod.cc
  paddle2onnx/mapper/tensor/unbind.cc
  paddle2onnx/mapper/tensor/unbind.h
  tests/test_unbind.py
Labels: Operator(New)

#1256 【Hackathon 6th No.56】Add deform conv2d op
  paddle2onnx/mapper/nn/deform_conv2d.cc
  paddle2onnx/mapper/nn/deform_conv2d.h
  tests/run.sh
  tests/test_deform_conv2d.py
Labels: PaddlePaddle Hackathon, Operator(New)

#1266 [Operator][Update] Support for the bitwise_and with bool data type
  paddle2onnx/mapper/tensor/bitwise_and.cc
  tests/test_bitwise_and.py
Labels: Bug, Operator(Update)
