Repository PaddlePaddle/Paddle2ONNX, pull requests merged in 2024-06, with the labels that each got.

#1269 [Operator][New] Add tril_triu op
  paddle2onnx/mapper/tensor/tril_triu.cc
  paddle2onnx/mapper/tensor/tril_triu.h
  tests/test_tril_triu.py
Labels: Operator(New)

#1270 [Operator][New] Add empty op
  paddle2onnx/mapper/tensor/empty.cc
  paddle2onnx/mapper/tensor/empty.h
  tests/test_empty.py
Labels: Operator(New)

#1274 [Operator][Update] Update split for opset18
  paddle2onnx/mapper/tensor/split.cc
  paddle2onnx/mapper/tensor/split.h
  tests/test_split.py
Labels: Operator(Update)

#1288 CI support aarch64
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
Labels: Bug, CI

#1298 paddle2onnx tech walkthrough doc
  docs/README.md
  docs/tech_walkthrough/paddle2onnx_tech_walkthrough.ipynb
Labels: Doc
