Repository PaddlePaddle/Paddle2ONNX, pull requests merged in 2024-08, with the labels that each got.

#1343 Fixed RKNN Bug and Remove Unuseful
  .gitignore
  paddle2onnx/mapper/quantize_helper.cc
Labels: RKNPU2, Operator(Update)

#1344 [Docs] Add onnxslim reference
  README.md
  README_en.md
Labels: Doc

#1355 Fixed matmul bug when export to rknn
  .gitignore
  VERSION_NUMBER
  paddle2onnx/mapper/activation/hard_swish.cc
  paddle2onnx/mapper/activation/hard_swish.h
  paddle2onnx/mapper/quantize_helper.cc
  paddle2onnx/mapper/quantize_helper.h
  tests/test_auto_scan_hardswish.py
  tests/test_hardswish.py
Labels: Bug, RKNPU2, Operator(Update)
