Repository PaddlePaddle/Paddle2ONNX, pull requests merged in 2024-07, with the labels that each got.

#1268 【Hackathon 6th No.58】support model convert from fp32 to fp16
  paddle2onnx/mapper/nn/pool2d.cc
  paddle2onnx/mapper/nn/pool2d.h
  paddle2onnx/mapper/nn/pool3d.cc
  paddle2onnx/mapper/nn/pool3d.h
  paddle2onnx/mapper/tensor/fill_constant.cc
  paddle2onnx/mapper/tensor/matmul.cc
  paddle2onnx/mapper/tensor/matmul.h
  paddle2onnx/mapper/tensor/matmul_v2.cc
  paddle2onnx/mapper/tensor/matmul_v2.h
  paddle2onnx/parser/parser.cc
  tests/run.sh
  tests/test_resnet_fp16.py
Labels: PaddlePaddle Hackathon, Operator(Update)

#1324 [Operator][New] Add conditional_block select_input
  paddle2onnx/mapper/activation/activation.cc
  paddle2onnx/mapper/activation/activation.h
  paddle2onnx/mapper/exporter.cc
  paddle2onnx/mapper/exporter.h
  paddle2onnx/mapper/loop.cc
  paddle2onnx/mapper/onnx_helper.cc
  paddle2onnx/mapper/onnx_helper.h
  paddle2onnx/mapper/tensor/elementwise.cc
  paddle2onnx/mapper/tensor/elementwise.h
  tests/run.sh
  tests/test_ifelse.py
Labels: Operator(New)

#1327 Update command
  paddle2onnx/command.py
Labels: Bug
