Repository PaddlePaddle/Paddle2ONNX, pull requests merged in 2024-02, with the labels that each got.

#1188 [Bug][CI] Fix the bug where elementwise floordiv only performs div without floor
  paddle2onnx/mapper/elementwise.cc
Labels: bug, CI

#1133 [Docs] Fix docs and breaking var name typos
  Paddle2Caffe/paddle2caffe/caffe_helper/caffe.proto
  Paddle2Caffe/paddle2caffe/op_mapper/tensor.py
  docs/zh/FAQ.md
  experimental/openvino_ppdet/nms_mapper.py
  model_zoo/ocr/infer.py
  paddle2onnx/cpp2py_export.cc
  paddle2onnx/legacy/constant/op_mapping_status.py
  paddle2onnx/legacy/op_mapper/detection/box_coder.py
  paddle2onnx/legacy/op_mapper/detection/density_prior_box.py
  paddle2onnx/legacy/op_mapper/detection/multiclass_nms.py
  paddle2onnx/legacy/op_mapper/detection/prior_box.py
  paddle2onnx/legacy/op_mapper/detection/yolo_box.py
  paddle2onnx/legacy/op_mapper/sequence/im2sequence.py
  paddle2onnx/legacy/op_mapper/tensor.py
  paddle2onnx/mapper/tensor/flip.cc
  paddle2onnx/optimizer/fuse_constant_reshape.h
  setup.py
  setup_dev.py
Labels: doc

#1192 [Bug][CI] Rewrite useful tests and delete useless tests
  tests/run.sh
  tests/test_auto_scan_expand.py
  tests/test_auto_scan_expand_v2.py
  tests/test_auto_scan_flatten2.py
  tests/test_auto_scan_generate_proposals_v2.py
  tests/test_auto_scan_matmul.py
  tests/test_auto_scan_matmul_v2.py
  tests/test_auto_scan_mean.py
  tests/test_auto_scan_mul.py
  tests/test_auto_scan_multiclass_nms_lod.py
  tests/test_auto_scan_multiclass_nms_tensor.py
  tests/test_auto_scan_norm.py
  tests/test_expand_as.py
Labels: bug, CI

#1193 [Bug][CI] Update ONNXRuntime version and Fixed bug in test_MaxPool2D
  tests/requirements.txt
  tests/run.sh
  tests/test_auto_scan_interpolate_v1_ops.py
  tests/test_auto_scan_isx_ops.py
  tests/test_auto_scan_squeeze2.py
  tests/test_auto_scan_top_k.py
  tests/test_auto_scan_top_k_v2.py
  tests/test_nn_MaxPool2D.py
  tests/test_split.py
Labels: bug, CI

#1196 [Remove][legacy] Delete legacy
  README.md
  paddle2onnx/legacy/__init__.py
  paddle2onnx/legacy/command.py
  paddle2onnx/legacy/constant/__init__.py
  paddle2onnx/legacy/constant/constant.py
  paddle2onnx/legacy/constant/dtypes.py
  paddle2onnx/legacy/constant/op_mapping_status.py
  paddle2onnx/legacy/convert.py
  paddle2onnx/legacy/graph/__init__.py
  paddle2onnx/legacy/graph/dygraph_helper.py
  paddle2onnx/legacy/graph/graph.py
  paddle2onnx/legacy/graph/graph_helper.py
  paddle2onnx/legacy/graph/onnx_graph.py
  paddle2onnx/legacy/graph/paddle_graph.py
  paddle2onnx/legacy/op_mapper/__init__.py
  paddle2onnx/legacy/op_mapper/activation.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/__init__.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/anchor_generator.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/box_clip.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/collect_fpn_proposals.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/deformable_conv.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/distribute_fpn_proposals.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/generate_proposals.py
  paddle2onnx/legacy/op_mapper/custom_paddle_op/grid_sampler.py
  paddle2onnx/legacy/op_mapper/detection/__init__.py
  paddle2onnx/legacy/op_mapper/detection/box_coder.py
  paddle2onnx/legacy/op_mapper/detection/density_prior_box.py
  paddle2onnx/legacy/op_mapper/detection/multiclass_nms.py
  paddle2onnx/legacy/op_mapper/detection/prior_box.py
  paddle2onnx/legacy/op_mapper/detection/yolo_box.py
  paddle2onnx/legacy/op_mapper/logic.py
  paddle2onnx/legacy/op_mapper/mapper_helper.py
  paddle2onnx/legacy/op_mapper/math.py
  paddle2onnx/legacy/op_mapper/nn.py
  paddle2onnx/legacy/op_mapper/op_mapper.py
  paddle2onnx/legacy/op_mapper/search.py
  paddle2onnx/legacy/op_mapper/sequence/__init__.py
  paddle2onnx/legacy/op_mapper/sequence/im2sequence.py
  paddle2onnx/legacy/op_mapper/tensor.py
  paddle2onnx/legacy/passes/__init__.py
  paddle2onnx/legacy/passes/dumplicate_names_pass.py
  paddle2onnx/legacy/passes/inplace_node_pass.py
  paddle2onnx/legacy/passes/pass_manager.py
Labels: remove unuesful

#1197 [Operator][Update] Update swish for paddlepaddle2.5
  paddle2onnx/mapper/activation.cc
Labels: update operator

#1198 [Operator][Update] Update relu6 for paddlepaddle2.5
  paddle2onnx/mapper/activation.cc
  tests/run.sh
Labels: update operator

#1199 [Remove][Command] Remove enable_dev_version
  paddle2onnx/command.py
Labels: remove unuseful

#1201 [Remove][legacy] remove legacy
  paddle2onnx/__init__.py
Labels: remove unuseful

#1200 [Remove][Command] Remove output_names and input_shape_dict
  README.md
  paddle2onnx/command.py
Labels: remove unuseful
